### ISSUE TITLE
One of the conditions in the query is invalid

### ISSUE THREAD

**Issue by markjmuellerjr** [crealytics/adwords_scripts#1]
When running a preview on this script it throws this error after finding all of the accounts and begins processing the first out of 4 accounts listed in the spreadsheet. How can I go about fixing the Error: One of the conditions in the query is invalid?

**Comment by nightscape** [comment]
I guess you are referring to the emergency_stop script? I don't know that one by heart, but it seems that there are only two places where a query condition is built: [here](https://github.com/crealytics/adwords_scripts/blob/master/src/emergency_stop/EmergencyStop.js#L122-L123) and [here](https://github.com/crealytics/adwords_scripts/blob/master/src/emergency_stop/EmergencyStop.js#L141-L144).
Can you try and add some `Logger.log` statements before, between and after those lines to find out which one exactly is failing?

**Comment by alexlytics** [comment]
Error occured, cause no label was found in account. Fixed in latest version.
